package nallar.ps2edit.ui.viewer;

import com.google.common.html.HtmlEscapers;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.val;
import me.nallar.jdds.JDDS;
import nallar.ps2edit.Assets;
import nallar.ps2edit.PackFile;
import nallar.ps2edit.Patcher;
import nallar.ps2edit.Paths;
import nallar.ps2edit.util.Throw;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.util.List;

public class Viewer {
	private final Map<String, PackFile.Entry> assetsMap;
	private final List<String> assetsList;
	private final Paths path;
	private final Assets assets;
	private final Console console;
	private JTextField searchField;
	private JList<String> list;
	private JPanel panel;
	private JLabel label;
	private JScrollPane leftScrollPane;
	private JScrollPane rightScrollPane;
	private JSplitPane splitPane;
	private JButton patchAndRunButton;

	public Viewer(Console console) {
		this.console = console;
		path = new Paths();
		assets = new Assets(path, false);
		assetsMap = assets.getFiles();
		assetsList = new ArrayList<>(assetsMap.keySet());
		Collections.sort(assetsList);
		list.addListSelectionListener((e) -> {
			if (!e.getValueIsAdjusting())
				updateSelection();
		});
		list.addMouseListener(new FileListListener(list));
		searchField.getDocument().addDocumentListener(new DocumentListener() {
			@Override
			public void insertUpdate(DocumentEvent e) {
				handleSearch();
			}

			@Override
			public void removeUpdate(DocumentEvent e) {
				handleSearch();
			}

			@Override
			public void changedUpdate(DocumentEvent e) {
				handleSearch();
			}
		});
		leftScrollPane.getVerticalScrollBar().setUnitIncrement(20);
		rightScrollPane.getVerticalScrollBar().setUnitIncrement(20);
		handleSearch();
		patchAndRunButton.addActionListener(e -> {
			launchGame();
		});
	}

	private static String convertStringForLabel(String stringData) {
		stringData = HtmlEscapers.htmlEscaper().escape(stringData);
		stringData = stringData.replace("\r\n", "<br>");
		stringData = stringData.replace("\n", "<br>");
		return "<html>" + stringData + "</html>";
	}

	public static void main(String[] args) {
		val console = Console.create();

		JFrame frame = new JFrame("Viewer");
		frame.setContentPane(new Viewer(console).panel);
		frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		frame.pack();
		frame.setVisible(true);
	}

	private void launchGame() {
		new Thread(() -> {
			console.panel.grabFocus();
			Patcher.main(path);
		}).start();
	}

	private void handleSearch() {
		List<String> strings = searchAssets(searchField.getText());
		list.setListData(strings.toArray(new String[strings.size()]));
	}

	private List<String> searchAssets(String search) {
		if (search.isEmpty())
			return getReplacements();

		search = search.toLowerCase();
		val results = new ArrayList<String>();
		for (String asset : assetsList) {
			if (asset.toLowerCase().contains(search))
				results.add(asset);
		}

		return results.size() > 25000 ? results.subList(0, 25000) : results;
	}

	private List<String> getReplacements() {
		val list = new ArrayList<String>();

		val replacementsArray = path.replacementsDir.list();

		List<String> replacements = replacementsArray == null ? Collections.emptyList() : Arrays.asList(replacementsArray);

		list.add("Showing " + replacements.size() + " replacement files.");
		list.add("Enter text in the search box above to search all PS2 files.");
		list.add("Right click -> edit to open the file for editing.");

		list.addAll(replacements);

		return list;
	}

	private void updateSelection() {
		val selected = list.getSelectedValue();
		val entry = assetsMap.get(selected);

		if (selected == null || selected.isEmpty())
			return;

		val i = selected.lastIndexOf('.');
		val type = selected.substring(i + 1, selected.length()).toLowerCase();
		label.setText(null);
		label.setIcon(null);

		if (entry == null)
			return;

		entry.getPackFile().openRead();
		try {
			switch (type) {
				case "xml":
				case "txt":
				case "cfg":
				case "ini":
				case "props":
					// plain text
					label.setText(convertStringForLabel(entry.getStringData()));
					break;
				case "dds":
					// compressed DDS image
					label.setIcon(new ImageIcon(JDDS.readDDS(entry.getData())));
					break;
				default:
					label.setText("Can not preview this file type");
			}
		} finally {
			entry.getPackFile().close();
		}
	}

	private void createUIComponents() {
		// TODO: place custom component creation code here
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel = new JPanel();
		panel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
		searchField = new JTextField();
		searchField.setToolTipText("File Search");
		panel.add(searchField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(400, -1), null, 0, false));
		patchAndRunButton = new JButton();
		patchAndRunButton.setText("Patch and Run");
		panel.add(patchAndRunButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		splitPane = new JSplitPane();
		splitPane.setContinuousLayout(false);
		splitPane.setEnabled(true);
		splitPane.setResizeWeight(0.2);
		panel.add(splitPane, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(500, 500), null, 0, false));
		rightScrollPane = new JScrollPane();
		splitPane.setLeftComponent(rightScrollPane);
		list = new JList();
		final DefaultListModel defaultListModel1 = new DefaultListModel();
		list.setModel(defaultListModel1);
		rightScrollPane.setViewportView(list);
		leftScrollPane = new JScrollPane();
		splitPane.setRightComponent(leftScrollPane);
		label = new JLabel();
		label.setText("");
		leftScrollPane.setViewportView(label);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel;
	}

	private class FileListListener implements MouseListener {
		private JList<String> list;
		private JPopupMenu menu;

		public FileListListener(JList<String> list) {
			this.list = list;
			this.menu = new JPopupMenu();

			addMenuItem("Edit", (e) -> {
				String selectedFile = list.getSelectedValue();
				PackFile.Entry asset = assetsMap.get(selectedFile);

				if (asset == null) {
					return;
				}

				File replacement = new File(path.replacementsDir, selectedFile);
				if (!replacement.exists()) {
					asset.getPackFile().openRead();
					try {
						byte[] data = asset.getData();
						Files.write(replacement.toPath(), data);
					} catch (IOException e1) {
						throw Throw.sneaky(e1);
					} finally {
						asset.getPackFile().close();
					}
				}
				if (Desktop.isDesktopSupported()) {
					try {
						Desktop.getDesktop().open(path.replacementsDir);
					} catch (IOException e1) {
						throw Throw.sneaky(e1);
					}
				}
			});
		}

		private void addMenuItem(String name, ActionListener l) {
			JMenuItem item = new JMenuItem(name);
			item.addActionListener(l);
			menu.add(item);
		}

		@Override
		public void mouseClicked(MouseEvent e) {
			if (!SwingUtilities.isRightMouseButton(e))
				return;

			list.setSelectedIndex(list.locationToIndex(e.getPoint()));
			menu.show(e.getComponent(), e.getX(), e.getY());
		}

		@Override
		public void mousePressed(MouseEvent e) {
		}

		@Override
		public void mouseReleased(MouseEvent e) {
		}

		@Override
		public void mouseEntered(MouseEvent e) {
		}

		@Override
		public void mouseExited(MouseEvent e) {
		}

	}

}
