package nallar.ps2edit.ui.viewer;

import com.google.common.html.HtmlEscapers;
import lombok.val;
import me.nallar.jdds.JDDS;
import nallar.ps2edit.Assets;
import nallar.ps2edit.PackFile;
import nallar.ps2edit.Paths;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.util.*;
import java.util.List;

public class Viewer {
	private final Map<String, PackFile.Entry> assetsMap;
	private final List<String> assetsList;
	private final Paths path;
	private final Assets assets;
	private JTextField searchField;
	private JList<String> list;
	private JPanel panel;
	private JLabel label;
	private JScrollPane leftScrollPane;
	private JScrollPane rightScrollPane;
	private JSplitPane splitPane;

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	public Viewer() {
		path = new Paths();
		assets = new Assets(path, false);
		assetsMap = assets.getFiles();
		assetsList = new ArrayList<>(assetsMap.keySet());
		Collections.sort(assetsList);
		list.addListSelectionListener((e) -> {
			if (!e.getValueIsAdjusting())
				updateSelection();
		});
		searchField.getDocument().addDocumentListener(new DocumentListener() {
			@Override
			public void insertUpdate(DocumentEvent e) {
				change();
			}

			@Override
			public void removeUpdate(DocumentEvent e) {
				change();
			}

			@Override
			public void changedUpdate(DocumentEvent e) {
				change();
			}

			private void change() {
				List<String> strings = searchAssets(searchField.getText());
				list.setListData(strings.toArray(new String[strings.size()]));
			}
		});
		leftScrollPane.getVerticalScrollBar().setUnitIncrement(20);
		rightScrollPane.getVerticalScrollBar().setUnitIncrement(20);
	}

	private static String convertStringForLabel(String stringData) {
		stringData = HtmlEscapers.htmlEscaper().escape(stringData);
		stringData = stringData.replace("\r\n", "<br>");
		stringData = stringData.replace("\n", "<br>");
		return "<html>" + stringData + "</html>";
	}

	public static void main(String[] args) {
		JFrame frame = new JFrame("Viewer");
		frame.setContentPane(new Viewer().panel);
		frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		frame.pack();
		frame.setVisible(true);
	}

	private List<String> searchAssets(String search) {
		if (search.isEmpty())
			return getReplacements();

		search = search.toLowerCase();
		val results = new ArrayList<String>();
		for (String asset : assetsList) {
			if (asset.toLowerCase().contains(search))
				results.add(asset);
		}

		return results.size() > 25000 ? results.subList(0, 25000) : results;
	}

	private List<String> getReplacements() {
		val list = path.replacementsDir.list();
		return list == null ? Collections.emptyList() : Arrays.asList(list);
	}

	private void updateSelection() {
		val selected = list.getSelectedValue();
		val entry = assetsMap.get(selected);

		if (entry == null)
			return;

		entry.getPackFile().openRead();

		val i = selected.lastIndexOf('.');
		val type = selected.substring(i + 1, selected.length());
		label.setText(null);
		label.setIcon(null);
		try {
			switch (type) {
				case "xml":
				case "txt":
				case "cfg":
				case "ini":
					// plain text
					label.setText(convertStringForLabel(entry.getStringData()));
					break;
				case "dds":
					// compressed DDS image
					label.setIcon(new ImageIcon(JDDS.readDDS(entry.getData())));
					break;
				default:
					label.setText("Can not preview this file type");
			}
		} finally {
			entry.getPackFile().close();
		}
	}

	private void createUIComponents() {
		// TODO: place custom component creation code here
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel = new JPanel();
		panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
		final JSplitPane splitPane1 = new JSplitPane();
		splitPane1.setContinuousLayout(false);
		splitPane1.setEnabled(true);
		splitPane1.setResizeWeight(0.2);
		panel.add(splitPane1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
		rightScrollPane = new JScrollPane();
		splitPane1.setLeftComponent(rightScrollPane);
		list = new JList();
		final DefaultListModel defaultListModel1 = new DefaultListModel();
		list.setModel(defaultListModel1);
		rightScrollPane.setViewportView(list);
		leftScrollPane = new JScrollPane();
		splitPane1.setRightComponent(leftScrollPane);
		label = new JLabel();
		label.setText("");
		leftScrollPane.setViewportView(label);
		searchField = new JTextField();
		panel.add(searchField, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel;
	}
}
